import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import {useEffect, useState} from "react";
import {ListProject} from "../components/ListProject";
import {Menu} from "../components/Menu";
import {Footer} from "../components/Footer";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {


    const [api, setAPI] = useState([])

    useEffect(() => {

        async function getProjects(){
            try{
                const response = await fetch("/oracles.json", {
                    method: "GET",
                }).then( (res) => res.json()).then((data) => setAPI(data))
            }catch (error){
                console.log(error)
            }
        }
        getProjects()
    }, [])

    return (
        <>
            <Head>
                <title>Nuls Oracles</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="icon" href="/neii.png" />
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
                <link
                    href="https://fonts.googleapis.com/css2?family=Arimo:ital,wght@0,400..700;1,400..700&display=swap"
                    rel="stylesheet"/>

            </Head>
            <main className={styles.main} style={{fontFamily:"Arimo", backgroundImage: "linear-gradient(180deg,#0c111c,#0f1421 14.87%,#10131a 29.77%,#19191b 50%)"}}>

                <Menu/>


                <div style={{backgroundColor:"white", marginTop:"40px", minWidth:"300px", fontFamily:"Arimo", padding:"10px", borderRadius:"10px", width:"35%", marginTop:"90px"}}>
                    <div style={{textAlign:"center", fontWeight:"bold",padding:"15px", fontSize:"18px"}}>
                        Claim Your Dividends
                    </div>
                    <div style={{padding:"5px"}}>
                        <div style={{display:"flex", justifyContent:"space-between", padding:"8px"}}>
                            <div>
                                Your Nuls Oracle Holdings
                            </div>
                            <div>
                                30.0 NORC
                            </div>
                        </div>
                        <div style={{display:"flex", justifyContent:"space-between", padding:"8px"}}>
                            <div>
                                Unclaimed Earnings
                            </div>
                            <div>
                                30.0 NULS
                            </div>
                        </div>
                        <div style={{display:"flex", justifyContent:"space-between", padding:"8px"}}>
                            <div>
                                All Time Earnings
                            </div>
                            <div>
                                30.0 NULS
                            </div>
                        </div>
                        <div style={{textAlign:"center", marginTop:"20px"}}>
                            <button
                            style={{
                                padding:"10px",
                                borderRadius:"4px",
                                backgroundColor:"rgb(50, 224, 141)",
                                border:"0px solid",
                                color:"white",
                                cursor:"pointer",
                                width:"80%",
                                fontWeight:"bold"
                            }}
                            >Claim</button>
                        </div>
                    </div>

                </div>


               <Footer/>
            </main>
        </>
    )
}
